# Generated by Django 4.0.2 on 2022-02-18 03:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('lido', models.CharField(max_length=1)),
                ('emprestado', models.CharField(max_length=1)),
            ],
        ),
    ]
